database:
  url: postgresql://myuser:mypassword@localhost:5432/mydatabase
github:
  # 공통 GitHub API 토큰 (모든 사용자에게 적용되는 기본값)
  api_token: "your_common_github_token_here"
admin: # 유저 정보 등록 등 관리자 권한이 필요한 API에 대한 인증 키
  api_key: admin_secret_key_12345

